import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type LangCode = "en" | "hi" | "mr" | "ta";

const translations: Record<string, Record<LangCode, string>> = {
  app_name: { en: "CiviConnect", hi: "CiviConnect", mr: "CiviConnect", ta: "CiviConnect" },
  powered_by: {
    en: "Powered by Smart City Initiative",
    hi: "स्मार्ट सिटी पहल द्वारा संचालित",
    mr: "स्मार्ट सिटी उपक्रमाद्वारे समर्थित",
    ta: "ஸ்மார்ட் சிட்டி முயற்சியால் இயக்கப்படுகிறது",
  },
  footer_tagline: {
    en: "CiviConnect - Unified Civic Utility Kiosk",
    hi: "CiviConnect - Unified Civic Utility Kiosk",
    mr: "CiviConnect - Unified Civic Utility Kiosk",
    ta: "CiviConnect - Unified Civic Utility Kiosk",
  },
  step_2_of_5: { en: "Step 2 of 5", hi: "5 में से चरण 2", mr: "5 पैकी चरण 2", ta: "5 இல் 2-ஆம் படி" },
  step_3_of_5: { en: "Step 3 of 5", hi: "5 में से चरण 3", mr: "5 पैकी चरण 3", ta: "5 இல் 3-ஆம் படி" },
  step_4_of_5: { en: "Step 4 of 5", hi: "5 में से चरण 4", mr: "5 पैकी चरण 4", ta: "5 இல் 4-ஆம் படி" },
  welcome_subtitle: {
    en: "Your Unified Smart Kiosk for Urban Civic Utility Services",
    hi: "शहरी नागरिक सेवाओं के लिए आपका एकीकृत स्मार्ट कियोस्क",
    mr: "शहरी नागरिक सेवांसाठी तुमचा एकात्मिक स्मार्ट किऑस्क",
    ta: "நகர்ப்புற குடிமக்கள் சேவைகளுக்கான உங்கள் ஒருங்கிணைந்த ஸ்மார்ட் கியோஸ்க்",
  },
  service_electricity: { en: "Electricity", hi: "बिजली", mr: "वीज", ta: "மின்சாரம்" },
  service_gas: { en: "Gas", hi: "गैस", mr: "गॅस", ta: "எரிவாயு" },
  service_municipal: { en: "Municipal", hi: "नगरपालिका", mr: "महानगरपालिका", ta: "நகராட்சி" },
  touch_to_begin: { en: "Touch to Begin", hi: "शुरू करने के लिए स्पर्श करें", mr: "सुरू करण्यासाठी स्पर्श करा", ta: "தொடங்க தொடவும்" },
  security_badge: {
    en: "AES-256 Encrypted • PCI DSS Compliant",
    hi: "AES-256 एन्क्रिप्टेड • PCI DSS अनुरूप",
    mr: "AES-256 एन्क्रिप्टेड • PCI DSS अनुरूप",
    ta: "AES-256 குறியாக்கம் • PCI DSS இணக்கம்",
  },
  select_language: { en: "Select Your Language", hi: "अपनी भाषा चुनें", mr: "तुमची भाषा निवडा", ta: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்" },
  language_hint: { en: "Choose your preferred language", hi: "अपनी पसंदीदा भाषा चुनें", mr: "आपली पसंतीची भाषा निवडा", ta: "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்" },
  language_english: { en: "English", hi: "अंग्रेज़ी", mr: "इंग्रजी", ta: "ஆங்கிலம்" },
  language_hindi: { en: "Hindi", hi: "हिंदी", mr: "हिंदी", ta: "இந்தி" },
  language_marathi: { en: "Marathi", hi: "मराठी", mr: "मराठी", ta: "மராத்தி" },
  language_tamil: { en: "Tamil", hi: "तमिल", mr: "तामिळ", ta: "தமிழ்" },
  auth_title: { en: "Authentication", hi: "प्रमाणीकरण", mr: "प्रमाणीकरण", ta: "அங்கீகாரம்" },
  enter_phone: { en: "Enter Phone Number", hi: "फोन नंबर दर्ज करें", mr: "फोन नंबर टाका", ta: "தொலைபேசி எண்ணை உள்ளிடவும்" },
  send_otp_help: {
    en: "We'll send a 6-digit OTP to verify your identity",
    hi: "पहचान सत्यापित करने के लिए 6 अंकों का OTP भेजा जाएगा",
    mr: "ओळख पडताळणीसाठी 6 अंकी OTP पाठवला जाईल",
    ta: "அடையாளத்தை சரிபார்க்க 6 இலக்க OTP அனுப்பப்படும்",
  },
  aadhaar_optional: { en: "Aadhaar (optional)", hi: "आधार (वैकल्पिक)", mr: "आधार (ऐच्छिक)", ta: "ஆதார் (விருப்பம்)" },
  send_otp: { en: "Send OTP", hi: "OTP भेजें", mr: "OTP पाठवा", ta: "OTP அனுப்பவும்" },
  sending_otp: { en: "Sending OTP...", hi: "OTP भेजा जा रहा है...", mr: "OTP पाठवत आहे...", ta: "OTP அனுப்பப்படுகிறது..." },
  verify_otp: { en: "Verify OTP", hi: "OTP सत्यापित करें", mr: "OTP पडताळा", ta: "OTP சரிபார்க்கவும்" },
  otp_sent_to: { en: "Enter the 6-digit code sent to", hi: "भेजा गया 6 अंकों का कोड दर्ज करें", mr: "पाठवलेला 6 अंकी कोड टाका", ta: "அனுப்பிய 6 இலக்க குறியீட்டை உள்ளிடவும்" },
  verify_continue: { en: "Verify & Continue", hi: "सत्यापित करें और आगे बढ़ें", mr: "पडताळा आणि पुढे चला", ta: "சரிபார்த்து தொடரவும்" },
  verifying: { en: "Verifying...", hi: "सत्यापित हो रहा है...", mr: "पडताळणी सुरू आहे...", ta: "சரிபார்க்கப்படுகிறது..." },
  change_phone_number: { en: "Change phone number", hi: "फोन नंबर बदलें", mr: "फोन नंबर बदला", ta: "தொலைபேசி எண்ணை மாற்றவும்" },
  dev_otp: { en: "Dev OTP", hi: "डेव OTP", mr: "डेव्ह OTP", ta: "டெவ் OTP" },
  otp_sent_success: { en: "OTP sent to", hi: "OTP भेजा गया", mr: "OTP पाठवला", ta: "OTP அனுப்பப்பட்டது" },
  otp_send_failed: { en: "Failed to send OTP", hi: "OTP भेजने में विफल", mr: "OTP पाठवण्यात अयशस्वी", ta: "OTP அனுப்ப முடியவில்லை" },
  verified_success: { en: "Verified successfully!", hi: "सफलतापूर्वक सत्यापित!", mr: "यशस्वी पडताळणी!", ta: "வெற்றிகரமாக சரிபார்க்கப்பட்டது!" },
  verify_failed: { en: "OTP verification failed", hi: "OTP सत्यापन विफल", mr: "OTP पडताळणी अयशस्वी", ta: "OTP சரிபார்ப்பு தோல்வியடைந்தது" },
  select_service_title: { en: "Select Service", hi: "सेवा चुनें", mr: "सेवा निवडा", ta: "சேவையைத் தேர்ந்தெடுக்கவும்" },
  services_heading: { en: "What can we help you with?", hi: "हम आपकी कैसे मदद कर सकते हैं?", mr: "आम्ही तुम्हाला कशी मदत करू?", ta: "நாங்கள் எப்படி உதவலாம்?" },
  services_subheading: { en: "Select a service to continue", hi: "जारी रखने के लिए सेवा चुनें", mr: "पुढे जाण्यासाठी सेवा निवडा", ta: "தொடர ஒரு சேவையைத் தேர்ந்தெடுக்கவும்" },
  service_electricity_desc: { en: "Pay bills, report outages", hi: "बिल भुगतान, बिजली बाधा रिपोर्ट", mr: "बिल भरा, खंडित वीज नोंदवा", ta: "பில் செலுத்தல், மின்தடை புகார்" },
  service_gas_desc: { en: "Pipeline gas, cylinder booking", hi: "पाइपलाइन गैस, सिलेंडर बुकिंग", mr: "पाईप गॅस, सिलिंडर बुकिंग", ta: "குழாய் எரிவாயு, சிலிண்டர் பதிவு" },
  service_water: { en: "Water Supply", hi: "जल आपूर्ति", mr: "पाणीपुरवठा", ta: "நீர் வழங்கல்" },
  service_water_desc: { en: "Water bills, connection", hi: "पानी बिल, कनेक्शन", mr: "पाणी बिल, जोडणी", ta: "நீர் பில், இணைப்பு" },
  service_waste: { en: "Waste Mgmt", hi: "कचरा प्रबंधन", mr: "कचरा व्यवस्थापन", ta: "கழிவு மேலாண்மை" },
  service_waste_desc: { en: "Collection, complaints", hi: "संग्रह, शिकायतें", mr: "संकलन, तक्रारी", ta: "சேகரிப்பு, புகார்கள்" },
  service_property: { en: "Property Tax", hi: "संपत्ति कर", mr: "मालमत्ता कर", ta: "சொத்து வரி" },
  service_property_desc: { en: "Payments, assessments", hi: "भुगतान, आकलन", mr: "देयके, मूल्यमापन", ta: "கட்டணங்கள், மதிப்பீடுகள்" },
  service_certificates: { en: "Certificates", hi: "प्रमाणपत्र", mr: "प्रमाणपत्रे", ta: "சான்றிதழ்கள்" },
  service_certificates_desc: { en: "Birth, death, domicile", hi: "जन्म, मृत्यु, निवास", mr: "जन्म, मृत्यू, अधिवास", ta: "பிறப்பு, இறப்பு, குடியிருப்பு" },
  file_complaint: { en: "File Complaint", hi: "शिकायत दर्ज करें", mr: "तक्रार नोंदवा", ta: "புகார் பதிவு" },
  file_complaint_desc: { en: "Report an issue", hi: "समस्या दर्ज करें", mr: "समस्या नोंदवा", ta: "சிக்கலை பதிவு செய்யவும்" },
  service_request: { en: "Service Request", hi: "सेवा अनुरोध", mr: "सेवा विनंती", ta: "சேவை கோரிக்கை" },
  service_request_desc: { en: "New connection, changes", hi: "नया कनेक्शन, बदलाव", mr: "नवीन जोडणी, बदल", ta: "புதிய இணைப்பு, மாற்றங்கள்" },
  track_status: { en: "Track Status", hi: "स्थिति ट्रैक करें", mr: "स्थिती ट्रॅक करा", ta: "நிலையை கண்காணிக்கவும்" },
  track_status_desc: { en: "Check complaint/request", hi: "शिकायत/अनुरोध जांचें", mr: "तक्रार/विनंती तपासा", ta: "புகார்/கோரிக்கை நிலை பார்க்க" },
  payment_enter_account: { en: "Enter Account ID", hi: "खाता आईडी दर्ज करें", mr: "खातेचा आयडी भरा", ta: "கணக்கு ஐடியை உள்ளிடவும்" },
  payment_scan_qr: { en: "Or scan the QR code on your bill", hi: "या अपने बिल का QR कोड स्कैन करें", mr: "किंवा बिलवरील QR कोड स्कॅन करा", ta: "அல்லது உங்கள் பில்லின் QR குறியீட்டை ஸ்கேன் செய்யவும்" },
  payment_gateway_note: { en: "You will be redirected to secure Stripe checkout", hi: "आपको सुरक्षित Stripe चेकआउट पर भेजा जाएगा", mr: "तुम्हाला सुरक्षित Stripe चेकआउटकडे वळवले जाईल", ta: "நீங்கள் பாதுகாப்பான Stripe checkout-க்கு மாற்றப்படுவீர்கள்" },
  pay_with_stripe: { en: "Pay with Stripe", hi: "Stripe से भुगतान करें", mr: "Stripe ने पेमेंट करा", ta: "Stripe மூலம் செலுத்தவும்" },
  fetch_bill_details: { en: "Fetch Bill Details", hi: "बिल विवरण प्राप्त करें", mr: "बिल तपशील मिळवा", ta: "பில் விவரங்களை பெறவும்" },
  lookup_failed: { en: "Failed to fetch bill details", hi: "बिल विवरण प्राप्त नहीं हुआ", mr: "बिल तपशील मिळवता आला नाही", ta: "பில் விவரங்களை பெற முடியவில்லை" },
  bill_summary: { en: "Bill Summary", hi: "बिल सारांश", mr: "बिल सारांश", ta: "பில் சுருக்கம்" },
  service: { en: "Service", hi: "सेवा", mr: "सेवा", ta: "சேவை" },
  account: { en: "Account", hi: "खाता", mr: "खाते", ta: "கணக்கு" },
  period: { en: "Period", hi: "अवधि", mr: "कालावधी", ta: "காலம்" },
  due_date: { en: "Due Date", hi: "नियत तिथि", mr: "देय तारीख", ta: "கடைசி தேதி" },
  amount_due: { en: "Amount Due", hi: "देय राशि", mr: "देय रक्कम", ta: "செலுத்த வேண்டிய தொகை" },
  pay_now: { en: "Pay Now", hi: "अभी भुगतान करें", mr: "आत्ता भरा", ta: "இப்போது செலுத்தவும்" },
  payment_processing: { en: "Processing Payment", hi: "भुगतान संसाधित हो रहा है", mr: "देयक प्रक्रिया सुरू आहे", ta: "கட்டணம் செயலாக்கப்படுகிறது" },
  payment_processing_wait: { en: "Please wait while we process your transaction...", hi: "लेनदेन पूरा होने तक कृपया प्रतीक्षा करें...", mr: "व्यवहार पूर्ण होईपर्यंत कृपया थांबा...", ta: "பரிவர்த்தனை நடைபெறும் வரை காத்திருக்கவும்..." },
  payment_success: { en: "Payment Successful!", hi: "भुगतान सफल!", mr: "पेमेंट यशस्वी!", ta: "கட்டணம் வெற்றி!" },
  transaction_id: { en: "Transaction ID:", hi: "लेनदेन आईडी:", mr: "व्यवहार आयडी:", ta: "பரிவர்த்தனை ஐடி:" },
  payment_failed: { en: "Payment failed", hi: "भुगतान विफल", mr: "पेमेंट अयशस्वी", ta: "கட்டணம் தோல்வியடைந்தது" },
  more_services: { en: "More Services", hi: "और सेवाएं", mr: "अधिक सेवा", ta: "மேலும் சேவைகள்" },
  done: { en: "Done", hi: "समाप्त", mr: "पूर्ण", ta: "முடிந்தது" },
  back: { en: "Back", hi: "वापस", mr: "मागे", ta: "பின்" },
  submit: { en: "Submit", hi: "जमा करें", mr: "सबमिट", ta: "சமர்ப்பிக்கவும்" },
  report_issue: { en: "Report an Issue", hi: "समस्या दर्ज करें", mr: "समस्या नोंदवा", ta: "சிக்கலை பதிவு செய்யவும்" },
  select_category: { en: "Select Category", hi: "श्रेणी चुनें", mr: "वर्ग निवडा", ta: "வகையை தேர்ந்தெடுக்கவும்" },
  issue_question: { en: "What type of issue are you facing?", hi: "आप किस प्रकार की समस्या का सामना कर रहे हैं?", mr: "तुम्हाला कोणती समस्या येत आहे?", ta: "நீங்கள் எந்த வகை சிக்கலை சந்திக்கிறீர்கள்?" },
  category_power_cut: { en: "Power Cut / Outage", hi: "बिजली कटौती / बाधा", mr: "वीज खंडित / आउटेज", ta: "மின்தடை / கோளாறு" },
  category_water_leakage: { en: "Water Leakage", hi: "जल रिसाव", mr: "पाणी गळती", ta: "நீர் கசிவு" },
  category_gas_issue: { en: "Gas Supply Issue", hi: "गैस आपूर्ति समस्या", mr: "गॅस पुरवठा समस्या", ta: "எரிவாயு விநியோக சிக்கல்" },
  category_waste_issue: { en: "Waste Collection", hi: "कचरा संग्रह", mr: "कचरा संकलन", ta: "கழிவு சேகரிப்பு" },
  describe_issue: { en: "Describe Issue", hi: "समस्या का विवरण दें", mr: "समस्येचे वर्णन करा", ta: "சிக்கலை விவரிக்கவும்" },
  category_label: { en: "Category:", hi: "श्रेणी:", mr: "वर्ग:", ta: "வகை:" },
  subject_placeholder: {
    en: "Subject (e.g., No power since morning)",
    hi: "विषय (जैसे: सुबह से बिजली नहीं)",
    mr: "विषय (उदा. सकाळपासून वीज नाही)",
    ta: "தலைப்பு (உதா: காலை முதல் மின்சாரம் இல்லை)",
  },
  issue_detail_placeholder: {
    en: "Describe the issue in detail...",
    hi: "समस्या का विस्तृत विवरण लिखें...",
    mr: "समस्येचे तपशीलवार वर्णन करा...",
    ta: "சிக்கலை விரிவாக எழுதவும்...",
  },
  fill_all_fields: { en: "Please fill in all fields", hi: "कृपया सभी फ़ील्ड भरें", mr: "कृपया सर्व फील्ड भरा", ta: "அனைத்து புலங்களையும் நிரப்பவும்" },
  registering_complaint: { en: "Registering Complaint", hi: "शिकायत दर्ज हो रही है", mr: "तक्रार नोंदणी सुरू आहे", ta: "புகார் பதிவு செய்யப்படுகிறது" },
  please_wait: { en: "Please wait...", hi: "कृपया प्रतीक्षा करें...", mr: "कृपया थांबा...", ta: "தயவுசெய்து காத்திருக்கவும்..." },
  complaint_registered: { en: "Complaint Registered!", hi: "शिकायत दर्ज हो गई!", mr: "तक्रार नोंदली गेली!", ta: "புகார் பதிவு செய்யப்பட்டது!" },
  reference_id: { en: "Reference ID:", hi: "संदर्भ आईडी:", mr: "संदर्भ आयडी:", ta: "குறிப்பு ஐடி:" },
  save_ref_to_track: { en: "Save this ID to track your complaint status", hi: "स्थिति ट्रैक करने के लिए इस आईडी को सुरक्षित रखें", mr: "स्थिती ट्रॅक करण्यासाठी हा आयडी जतन करा", ta: "நிலையை கண்காணிக்க இந்த ஐடியை சேமிக்கவும்" },
  complaint_success: { en: "Complaint registered successfully!", hi: "शिकायत सफलतापूर्वक दर्ज हुई!", mr: "तक्रार यशस्वी नोंदली!", ta: "புகார் வெற்றிகரமாக பதிவு செய்யப்பட்டது!" },
  complaint_failed: { en: "Failed to register complaint", hi: "शिकायत दर्ज करने में विफल", mr: "तक्रार नोंदवण्यात अयशस्वी", ta: "புகார் பதிவு செய்ய முடியவில்லை" },
  request_new: { en: "New Request", hi: "नया अनुरोध", mr: "नवीन विनंती", ta: "புதிய கோரிக்கை" },
  select_request_type: { en: "Select Request Type", hi: "अनुरोध प्रकार चुनें", mr: "विनंती प्रकार निवडा", ta: "கோரிக்கை வகையைத் தேர்ந்தெடுக்கவும்" },
  service_need_question: { en: "What service do you need?", hi: "आपको कौन सी सेवा चाहिए?", mr: "तुम्हाला कोणती सेवा हवी?", ta: "உங்களுக்கு எந்த சேவை வேண்டும்?" },
  req_new_connection: { en: "New Connection", hi: "नया कनेक्शन", mr: "नवीन जोडणी", ta: "புதிய இணைப்பு" },
  req_address_change: { en: "Address Change", hi: "पता परिवर्तन", mr: "पत्ता बदल", ta: "முகவரி மாற்றம்" },
  req_meter_replace: { en: "Meter Replacement", hi: "मीटर बदलना", mr: "मीटर बदल", ta: "மீட்டர் மாற்றம்" },
  req_name_correction: { en: "Name Correction", hi: "नाम सुधार", mr: "नाव दुरुस्ती", ta: "பெயர் திருத்தம்" },
  request_details: { en: "Request Details", hi: "अनुरोध विवरण", mr: "विनंती तपशील", ta: "கோரிக்கை விவரங்கள்" },
  type_label: { en: "Type:", hi: "प्रकार:", mr: "प्रकार:", ta: "வகை:" },
  full_name_placeholder: { en: "Full Name", hi: "पूरा नाम", mr: "पूर्ण नाव", ta: "முழு பெயர்" },
  request_detail_placeholder: { en: "Provide details about your request...", hi: "अपने अनुरोध का विवरण दें...", mr: "तुमच्या विनंतीबद्दल तपशील द्या...", ta: "உங்கள் கோரிக்கையின் விவரங்களை எழுதவும்..." },
  upload_docs_help: { en: "Upload up to 3 supporting documents (max 5MB each).", hi: "अधिकतम 3 दस्तावेज़ अपलोड करें (प्रत्येक 5MB तक)।", mr: "जास्तीत जास्त 3 कागदपत्रे अपलोड करा (प्रत्येकी 5MB).", ta: "அதிகபட்சம் 3 ஆவணங்கள் (ஒன்றுக்கு 5MB) பதிவேற்றலாம்." },
  submitting_request: { en: "Submitting Request", hi: "अनुरोध भेजा जा रहा है", mr: "विनंती सबमिट होत आहे", ta: "கோரிக்கை சமர்ப்பிக்கப்படுகிறது" },
  request_submitted: { en: "Request Submitted!", hi: "अनुरोध जमा हुआ!", mr: "विनंती सादर झाली!", ta: "கோரிக்கை சமர்ப்பிக்கப்பட்டது!" },
  use_ref_track_request: { en: "Use this ID to track your request status", hi: "स्थिति ट्रैक करने के लिए इस आईडी का उपयोग करें", mr: "स्थिती ट्रॅक करण्यासाठी हा आयडी वापरा", ta: "உங்கள் கோரிக்கை நிலையை பார்க்க இந்த ஐடியை பயன்படுத்தவும்" },
  request_success: { en: "Service request submitted!", hi: "सेवा अनुरोध जमा हुआ!", mr: "सेवा विनंती सादर झाली!", ta: "சேவை கோரிக்கை சமர்ப்பிக்கப்பட்டது!" },
  request_failed: { en: "Failed to submit request", hi: "अनुरोध जमा करने में विफल", mr: "विनंती सादर करण्यात अयशस्वी", ta: "கோரிக்கையை சமர்ப்பிக்க முடியவில்லை" },
  track_progress: { en: "Check Progress", hi: "प्रगति जांचें", mr: "प्रगती तपासा", ta: "முன்னேற்றத்தை பார்க்கவும்" },
  track_your_request: { en: "Track Your Request", hi: "अपना अनुरोध ट्रैक करें", mr: "तुमची विनंती ट्रॅक करा", ta: "உங்கள் கோரிக்கையை கண்காணிக்கவும்" },
  enter_reference_help: { en: "Enter your reference ID (CMP-xxx, SR-xxx, or TXN-xxx)", hi: "अपनी संदर्भ आईडी दर्ज करें (CMP-xxx, SR-xxx, या TXN-xxx)", mr: "तुमचा संदर्भ आयडी टाका (CMP-xxx, SR-xxx, किंवा TXN-xxx)", ta: "உங்கள் குறிப்பு ஐடியை உள்ளிடவும் (CMP-xxx, SR-xxx, அல்லது TXN-xxx)" },
  searching: { en: "Searching...", hi: "खोजा जा रहा है...", mr: "शोध चालू आहे...", ta: "தேடுகிறது..." },
  status_pending: { en: "Pending", hi: "लंबित", mr: "प्रलंबित", ta: "நிலுவை" },
  status_in_progress: { en: "In Progress", hi: "प्रगति में", mr: "प्रगतीत", ta: "செயல்பாட்டில்" },
  status_completed: { en: "Completed", hi: "पूर्ण", mr: "पूर्ण", ta: "நிறைவு" },
  status_rejected: { en: "Rejected", hi: "अस्वीकृत", mr: "नाकारले", ta: "நிராகரிக்கப்பட்டது" },
  type: { en: "Type", hi: "प्रकार", mr: "प्रकार", ta: "வகை" },
  date: { en: "Date", hi: "तिथि", mr: "तारीख", ta: "தேதி" },
  details: { en: "Details", hi: "विवरण", mr: "तपशील", ta: "விவரங்கள்" },
  timeline_submitted: { en: "Submitted", hi: "जमा", mr: "सादर", ta: "சமர்ப்பிக்கப்பட்டது" },
  timeline_in_progress: { en: "In Progress", hi: "प्रगति में", mr: "प्रगतीत", ta: "செயல்பாட்டில்" },
  timeline_completed: { en: "Completed", hi: "पूर्ण", mr: "पूर्ण", ta: "நிறைவு" },
  back_to_services: { en: "Back to Services", hi: "सेवाओं पर वापस", mr: "सेवांकडे परत", ta: "சேவைகளுக்கு திரும்பவும்" },
  no_records_found: { en: "No records found", hi: "कोई रिकॉर्ड नहीं मिला", mr: "रेकॉर्ड आढळला नाही", ta: "பதிவு எதுவும் இல்லை" },
  check_ref_try_again: { en: "Please check your reference ID and try again", hi: "कृपया संदर्भ आईडी जांचकर फिर प्रयास करें", mr: "कृपया संदर्भ आयडी तपासून पुन्हा प्रयत्न करा", ta: "குறிப்பு ஐடியை சரிபார்த்து மீண்டும் முயற்சிக்கவும்" },
  logout: { en: "Logout", hi: "लॉगआउट", mr: "लॉगआउट", ta: "வெளியேறு" },
  services_help_title: { en: "How to use this page", hi: "इस पेज का उपयोग कैसे करें", mr: "हे पेज कसे वापरावे", ta: "இந்தப் பக்கத்தை எப்படி பயன்படுத்துவது" },
  services_help_body: {
    en: "Choose a tile to continue. Payment tiles open bill lookup and payment flow, while Complaint, Service Request, and Track Status are for issue reporting, new requests, and status checking.",
    hi: "आगे बढ़ने के लिए एक विकल्प चुनें। पेमेंट विकल्प बिल खोज और भुगतान के लिए हैं, जबकि शिकायत, सेवा अनुरोध और स्थिति ट्रैकिंग अन्य सेवाओं के लिए हैं।",
    mr: "पुढे जाण्यासाठी एक पर्याय निवडा. पेमेंट पर्याय बिल शोध आणि पेमेंटसाठी आहेत, तर तक्रार, सेवा विनंती आणि स्थिती ट्रॅकिंग इतर सेवांसाठी आहेत.",
    ta: "தொடர ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும். கட்டண விருப்பங்கள் பில் தேடல் மற்றும் கட்டணத்திற்கு, புகார், சேவை கோரிக்கை மற்றும் நிலை கண்காணிப்பு மற்ற சேவைகளுக்கு பயன்படுத்தப்படுகின்றன.",
  },
  complaint_help_category: {
    en: "This feature is for unresolved civic utility issues. Select the closest category, then provide clear details on the next screen to help faster resolution.",
    hi: "यह सुविधा लंबित नागरिक सेवा समस्याओं के लिए है। सही श्रेणी चुनें और अगले चरण में स्पष्ट विवरण दें ताकि समाधान जल्दी हो सके।",
    mr: "ही सुविधा प्रलंबित नागरी सेवा समस्यांसाठी आहे. योग्य प्रकार निवडा आणि पुढील टप्प्यात स्पष्ट माहिती द्या, म्हणजे निराकरण लवकर होईल.",
    ta: "இந்த வசதி தீர்க்கப்படாத குடிமக்கள் சேவை பிரச்சினைகளுக்காகும். சரியான வகையைத் தேர்ந்தெடுத்து அடுத்த கட்டத்தில் தெளிவான விவரங்களை வழங்கவும்.",
  },
  complaint_help_details: {
    en: "Include location, time, and impact in your description. This improves triage accuracy and status updates.",
    hi: "विवरण में स्थान, समय और प्रभाव जरूर लिखें। इससे जांच और स्थिति अपडेट बेहतर होते हैं।",
    mr: "वर्णनात ठिकाण, वेळ आणि परिणाम नमूद करा. यामुळे तपासणी आणि स्थिती अपडेट अधिक अचूक होतात.",
    ta: "விவரத்தில் இடம், நேரம் மற்றும் தாக்கத்தை குறிப்பிடவும். இது செயலாக்க துல்லியத்தையும் நிலை புதுப்பிப்பையும் மேம்படுத்தும்.",
  },
  request_help_type: {
    en: "Use this for planned changes like new connection, address update, meter replacement, or name correction. Select the closest type to route your request correctly.",
    hi: "नई कनेक्शन, पता परिवर्तन, मीटर बदल या नाम सुधार जैसे अनुरोधों के लिए इसका उपयोग करें। सही प्रकार चुनने से अनुरोध सही विभाग में जाता है।",
    mr: "नवीन जोडणी, पत्ता बदल, मीटर बदल किंवा नाव दुरुस्ती अशा विनंत्यांसाठी हे वापरा. योग्य प्रकार निवडल्यास विनंती योग्य विभागाकडे जाते.",
    ta: "புதிய இணைப்பு, முகவரி மாற்றம், மீட்டர் மாற்றம் அல்லது பெயர் திருத்தம் போன்ற கோரிக்கைகளுக்கு இதைப் பயன்படுத்தவும். சரியான வகையைத் தேர்ந்தெடுத்தால் கோரிக்கை சரியான பிரிவிற்கு செல்கிறது.",
  },
  request_help_details: {
    en: "Add complete information and supporting files to reduce verification delays.",
    hi: "सत्यापन में देरी कम करने के लिए पूरी जानकारी और सहायक दस्तावेज़ जोड़ें।",
    mr: "पडताळणीतील विलंब कमी करण्यासाठी पूर्ण माहिती आणि पूरक कागदपत्रे जोडा.",
    ta: "சரிபார்ப்பு தாமதத்தை குறைக்க முழுமையான தகவலும் ஆதார கோப்புகளும் சேர்க்கவும்.",
  },
  tracking_help_input: {
    en: "Use the reference ID received after complaint, service request, or payment. Keep the exact prefix (CMP, SR, TXN) for accurate lookup.",
    hi: "शिकायत, सेवा अनुरोध या भुगतान के बाद मिला रेफरेंस आईडी उपयोग करें। सही खोज के लिए प्रीफिक्स (CMP, SR, TXN) जैसा है वैसा ही रखें।",
    mr: "तक्रार, सेवा विनंती किंवा पेमेंटनंतर मिळालेला संदर्भ आयडी वापरा. अचूक शोधासाठी प्रीफिक्स (CMP, SR, TXN) जसेच्या तसे ठेवा.",
    ta: "புகார், சேவை கோரிக்கை அல்லது கட்டணத்திற்குப் பின் கிடைத்த குறிப்பு ஐடியை பயன்படுத்தவும். துல்லியமான தேடலுக்கு முன்னொட்டு (CMP, SR, TXN) அதேபடி இருக்க வேண்டும்.",
  },
  session_timeout: { en: "Session Timeout", hi: "सत्र समाप्ति", mr: "सत्र कालबाह्य", ta: "அமர்வு காலாவதி" },
  session_expires_in: { en: "Your session will expire in", hi: "आपका सत्र समाप्त होगा", mr: "तुमचे सत्र संपेल", ta: "உங்கள் அமர்வு முடிவடையும்" },
  continue_session: { en: "Continue Session", hi: "सत्र जारी रखें", mr: "सत्र सुरू ठेवा", ta: "அமர்வை தொடரவும்" },
  not_found_title: { en: "Oops! Page not found", hi: "ओह! पेज नहीं मिला", mr: "अरेरे! पृष्ठ सापडले नाही", ta: "அச்சச்சோ! பக்கம் கிடைக்கவில்லை" },
  return_home: { en: "Return to Home", hi: "होम पर लौटें", mr: "मुखपृष्ठावर जा", ta: "முகப்புக்கு திரும்பவும்" },
  payment_account_placeholder: { en: "Enter account number", hi: "Enter account number", mr: "Enter account number", ta: "Enter account number" },
  demo_success_no_charge: { en: "Demo Success (No Charge)", hi: "Demo Success (No Charge)", mr: "Demo Success (No Charge)", ta: "Demo Success (No Charge)" },
  error_demo_payment: { en: "Unable to complete demo payment", hi: "Unable to complete demo payment", mr: "Unable to complete demo payment", ta: "Unable to complete demo payment" },
  error_create_checkout_session: { en: "Unable to create checkout session", hi: "Unable to create checkout session", mr: "Unable to create checkout session", ta: "Unable to create checkout session" },
  error_missing_txn_ref: { en: "Missing transaction reference", hi: "Missing transaction reference", mr: "Missing transaction reference", ta: "Missing transaction reference" },
  error_verify_demo_payment: { en: "Unable to verify demo payment", hi: "Unable to verify demo payment", mr: "Unable to verify demo payment", ta: "Unable to verify demo payment" },
  error_missing_session_id: { en: "Missing Stripe session id", hi: "Missing Stripe session id", mr: "Missing Stripe session id", ta: "Missing Stripe session id" },
  error_verify_payment_status: { en: "Unable to verify payment status", hi: "Unable to verify payment status", mr: "Unable to verify payment status", ta: "Unable to verify payment status" },
  or: { en: "OR", hi: "या", mr: "किंवा", ta: "அல்லது" },
  continue_with_aadhaar: { en: "Continue with Aadhaar", hi: "आधार के साथ जारी रखें", mr: "आधारसह पुढे जा", ta: "ஆதாருடன் தொடரவும்" },
  verify_with_aadhaar: { en: "Verify with Aadhaar", hi: "आधार से सत्यापित करें", mr: "आधारद्वारे पडताळा", ta: "ஆதாருடன் சரிபார்க்கவும்" },
  enter_12_digit_aadhaar: { en: "Enter 12-digit Aadhaar", hi: "12 अंकों का आधार दर्ज करें", mr: "12 अंकी आधार टाका", ta: "12 இலக்க ஆதாரை உள்ளிடவும்" },
  aadhaar_verification_failed: { en: "Aadhaar verification failed", hi: "आधार सत्यापन विफल", mr: "आधार पडताळणी अयशस्वी", ta: "ஆதார் சரிபார்ப்பு தோல்வியடைந்தது" },
  menu_profile: { en: "Profile", hi: "प्रोफ़ाइल", mr: "प्रोफाइल", ta: "சுயவிவரம்" },
  menu_my_account: { en: "My Account", hi: "मेरा खाता", mr: "माझे खाते", ta: "என் கணக்கு" },
  menu_view_profile: { en: "View Profile", hi: "प्रोफ़ाइल देखें", mr: "प्रोफाइल पहा", ta: "சுயவிவரம் பார்க்க" },
  menu_pending_bills: { en: "Pending Bills", hi: "लंबित बिल", mr: "प्रलंबित बिले", ta: "நிலுவை பில்கள்" },
  menu_notifications: { en: "Notifications", hi: "सूचनाएं", mr: "सूचना", ta: "அறிவிப்புகள்" },
  menu_reminders: { en: "Reminders", hi: "रिमाइंडर", mr: "स्मरणपत्रे", ta: "நினைவூட்டல்கள்" },
  menu_settings: { en: "Settings", hi: "सेटिंग्स", mr: "सेटिंग्ज", ta: "அமைப்புகள்" },
  menu_help: { en: "Help", hi: "सहायता", mr: "मदत", ta: "உதவி" },
  menu_downloads: { en: "My Downloads", hi: "मेरे डाउनलोड", mr: "माझे डाउनलोड", ta: "என் பதிவிறக்கங்கள்" },
  title_my_profile: { en: "My Profile", hi: "मेरी प्रोफ़ाइल", mr: "माझी प्रोफाइल", ta: "என் சுயவிவரம்" },
  resident_id: { en: "Resident ID", hi: "निवासी आईडी", mr: "निवासी आयडी", ta: "குடியிருப்பாளர் ஐடி" },
  identity_contact: { en: "Identity and Contact", hi: "पहचान और संपर्क", mr: "ओळख आणि संपर्क", ta: "அடையாளம் மற்றும் தொடர்பு" },
  address_ward_data: { en: "Address and Ward", hi: "पता और वार्ड", mr: "पत्ता आणि वॉर्ड", ta: "முகவரி மற்றும் வார்டு" },
  ward: { en: "Ward", hi: "वार्ड", mr: "वॉर्ड", ta: "வார்டு" },
  last_updated: { en: "Last Updated", hi: "अंतिम अपडेट", mr: "शेवटचे अद्यतन", ta: "கடைசி புதுப்பிப்பு" },
  upcoming_personal_reminders: { en: "Upcoming Personal Reminders", hi: "आगामी व्यक्तिगत रिमाइंडर", mr: "आगामी वैयक्तिक स्मरणपत्रे", ta: "வரவிருக்கும் தனிப்பட்ட நினைவூட்டல்கள்" },
  loading_profile: { en: "Loading profile...", hi: "प्रोफ़ाइल लोड हो रही है...", mr: "प्रोफाइल लोड होत आहे...", ta: "சுயவிவரம் ஏற்றப்படுகிறது..." },
  error_load_profile: { en: "Unable to load profile details", hi: "प्रोफ़ाइल विवरण लोड नहीं हो सके", mr: "प्रोफाइल तपशील लोड करता आले नाहीत", ta: "சுயவிவர விவரங்களை ஏற்ற முடியவில்லை" },
  subtitle_resident_details: { en: "Resident details and account information", hi: "निवासी विवरण और खाता जानकारी", mr: "निवासी तपशील आणि खाते माहिती", ta: "குடியிருப்பாளர் விவரங்கள் மற்றும் கணக்கு தகவல்" },
  subtitle_outstanding_payments: { en: "Outstanding utility payments", hi: "बकाया उपयोगिता भुगतान", mr: "थकित सेवा देयके", ta: "நிலுவை சேவை கட்டணங்கள்" },
  subtitle_recent_alerts: { en: "Recent alerts and updates", hi: "हाल की सूचनाएं और अपडेट", mr: "अलीकडील सूचना आणि अद्यतने", ta: "சமீபத்திய அறிவிப்புகள் மற்றும் புதுப்பிப்புகள்" },
  subtitle_upcoming_actions: { en: "Upcoming actions and due items", hi: "आगामी कार्य और देय आइटम", mr: "आगामी कृती आणि देय बाबी", ta: "வரவிருக்கும் செயல்கள் மற்றும் நிலுவை உருப்படிகள்" },
  subtitle_preferences_security: { en: "Preferences, alerts and security", hi: "प्राथमिकताएं, सूचनाएं और सुरक्षा", mr: "प्राधान्ये, सूचना आणि सुरक्षा", ta: "விருப்பங்கள், அறிவிப்புகள் மற்றும் பாதுகாப்பு" },
  subtitle_support_guidance: { en: "Support channels and guidance", hi: "सहायता चैनल और मार्गदर्शन", mr: "सहाय्य मार्ग आणि मार्गदर्शन", ta: "உதவி சேனல்கள் மற்றும் வழிகாட்டல்" },
  subtitle_receipt_library: { en: "Your receipt download library", hi: "आपकी रसीद डाउनलोड लाइब्रेरी", mr: "तुमची पावती डाउनलोड लायब्ररी", ta: "உங்கள் ரசீது பதிவிறக்க தொகுப்பு" },
  total_bills: { en: "Total Bills", hi: "कुल बिल", mr: "एकूण बिले", ta: "மொத்த பில்கள்" },
  total_due: { en: "Total Due", hi: "कुल बकाया", mr: "एकूण देय", ta: "மொத்த நிலுவை" },
  nearest_due_date: { en: "Nearest Due Date", hi: "निकटतम देय तिथि", mr: "सर्वात जवळची देय तारीख", ta: "அடுத்த நிலுவை தேதி" },
  not_available: { en: "Not available", hi: "उपलब्ध नहीं", mr: "उपलब्ध नाही", ta: "கிடைக்கவில்லை" },
  bill_reference: { en: "Bill Ref", hi: "बिल संदर्भ", mr: "बिल संदर्भ", ta: "பில் குறிப்பு" },
  due_by: { en: "Due by", hi: "देय तिथि", mr: "देय तारीख", ta: "செலுத்த வேண்டிய தேதி" },
  error_load_pending_bills: { en: "Unable to load pending bills", hi: "लंबित बिल लोड नहीं हो सके", mr: "प्रलंबित बिले लोड करता आली नाहीत", ta: "நிலுவை பில்களை ஏற்ற முடியவில்லை" },
  total_notifications: { en: "Total Notifications", hi: "कुल सूचनाएं", mr: "एकूण सूचना", ta: "மொத்த அறிவிப்புகள்" },
  unread: { en: "Unread", hi: "अपठित", mr: "न वाचलेले", ta: "படிக்காதவை" },
  read: { en: "Read", hi: "पढ़ा हुआ", mr: "वाचलेले", ta: "படிக்கப்பட்டவை" },
  new: { en: "New", hi: "नया", mr: "नवीन", ta: "புதியது" },
  error_load_notifications: { en: "Unable to load notifications", hi: "सूचनाएं लोड नहीं हो सकीं", mr: "सूचना लोड करता आल्या नाहीत", ta: "அறிவிப்புகளை ஏற்ற முடியவில்லை" },
  upcoming_reminders: { en: "Upcoming Reminders", hi: "आगामी रिमाइंडर", mr: "आगामी स्मरणपत्रे", ta: "வரவிருக்கும் நினைவூட்டல்கள்" },
  completed_reminders: { en: "Completed Reminders", hi: "पूर्ण रिमाइंडर", mr: "पूर्ण स्मरणपत्रे", ta: "முடிக்கப்பட்ட நினைவூட்டல்கள்" },
  error_load_reminders: { en: "Unable to load reminders", hi: "रिमाइंडर लोड नहीं हो सके", mr: "स्मरणपत्रे लोड करता आली नाहीत", ta: "நினைவூட்டல்களை ஏற்ற முடியவில்லை" },
  loading_settings: { en: "Loading settings...", hi: "सेटिंग्स लोड हो रही हैं...", mr: "सेटिंग्ज लोड होत आहेत...", ta: "அமைப்புகள் ஏற்றப்படுகின்றன..." },
  notif_receipt_preferences: { en: "Notifications and Receipt Preferences", hi: "सूचनाएं और रसीद प्राथमिकताएं", mr: "सूचना आणि पावती प्राधान्ये", ta: "அறிவிப்புகள் மற்றும் ரசீது விருப்பங்கள்" },
  language: { en: "Language", hi: "भाषा", mr: "भाषा", ta: "மொழி" },
  sms_alerts: { en: "SMS Alerts", hi: "SMS अलर्ट", mr: "SMS सूचना", ta: "SMS அறிவிப்புகள்" },
  email_alerts: { en: "Email Alerts", hi: "ईमेल अलर्ट", mr: "ईमेल सूचना", ta: "மின்னஞ்சல் அறிவிப்புகள்" },
  push_alerts: { en: "Push Alerts", hi: "पुश अलर्ट", mr: "पुश सूचना", ta: "புஷ் அறிவிப்புகள்" },
  paperless_receipts: { en: "Paperless Receipts", hi: "पेपरलेस रसीद", mr: "पेपरलेस पावती", ta: "காகிதமற்ற ரசீதுகள்" },
  enabled: { en: "Enabled", hi: "सक्रिय", mr: "सक्रिय", ta: "இயக்கப்பட்டது" },
  disabled: { en: "Disabled", hi: "निष्क्रिय", mr: "निष्क्रिय", ta: "முடக்கப்பட்டது" },
  accessibility_session: { en: "Accessibility and Session", hi: "सुगम्यता और सत्र", mr: "सुलभता आणि सत्र", ta: "அணுகல்திறன் மற்றும் அமர்வு" },
  kiosk_accessibility_mode: { en: "Kiosk Accessibility Mode", hi: "कियोस्क सुगम्यता मोड", mr: "किऑस्क सुलभता मोड", ta: "கியோஸ்க் அணுகல்திறன் முறை" },
  high_contrast_mode: { en: "High Contrast Mode", hi: "हाई कॉन्ट्रास्ट मोड", mr: "हाय कॉन्ट्रास्ट मोड", ta: "உயர் மாற்றம் முறை" },
  large_text_mode: { en: "Large Text Mode", hi: "बड़ा टेक्स्ट मोड", mr: "मोठा मजकूर मोड", ta: "பெரிய எழுத்து முறை" },
  auto_logout_window: { en: "Auto Logout Window", hi: "ऑटो लॉगआउट समय", mr: "ऑटो लॉगआउट वेळ", ta: "தானியங்கி வெளியேறும் நேரம்" },
  minutes_short: { en: "min", hi: "मिनट", mr: "मि", ta: "நிமி" },
  security_startup: { en: "Security and Startup", hi: "सुरक्षा और प्रारंभ", mr: "सुरक्षा आणि प्रारंभ", ta: "பாதுகாப்பு மற்றும் தொடக்கம்" },
  biometric_lock: { en: "Biometric Lock", hi: "बायोमेट्रिक लॉक", mr: "बायोमेट्रिक लॉक", ta: "உயிரணு பூட்டு" },
  default_service: { en: "Default Service", hi: "डिफ़ॉल्ट सेवा", mr: "डीफॉल्ट सेवा", ta: "இயல்புநிலை சேவை" },
  preferred_start_page: { en: "Preferred Start Page", hi: "पसंदीदा प्रारंभ पेज", mr: "प्राधान्य प्रारंभ पृष्ठ", ta: "விருப்பமான தொடக்க பக்கம்" },
  error_load_settings: { en: "Unable to load settings", hi: "सेटिंग्स लोड नहीं हो सकीं", mr: "सेटिंग्ज लोड करता आल्या नाहीत", ta: "அமைப்புகளை ஏற்ற முடியவில்லை" },
  contact_channels: { en: "Contact Channels", hi: "संपर्क चैनल", mr: "संपर्क मार्ग", ta: "தொடர்பு சேனல்கள்" },
  support_contact_line: { en: "Support Contact Line", hi: "सहायता संपर्क लाइन", mr: "सहाय्य संपर्क लाईन", ta: "உதவி தொடர்பு வரி" },
  support_sla: { en: "Typical support response time is under 15 minutes for payment and account issues.", hi: "भुगतान और खाता समस्याओं के लिए सहायता का सामान्य उत्तर समय 15 मिनट से कम है।", mr: "पेमेंट आणि खाते समस्यांसाठी सहाय्याचा प्रतिसाद वेळ साधारण 15 मिनिटांपेक्षा कमी असतो.", ta: "கட்டணம் மற்றும் கணக்கு பிரச்சினைகளுக்கு உதவி பதில் நேரம் பொதுவாக 15 நிமிடங்களுக்கு உட்பட்டது." },
  error_load_help: { en: "Unable to load help details", hi: "सहायता विवरण लोड नहीं हो सके", mr: "मदत तपशील लोड करता आले नाहीत", ta: "உதவி விவரங்களை ஏற்ற முடியவில்லை" },
  amount_short: { en: "Amount", hi: "राशि", mr: "रक्कम", ta: "தொகை" },
  downloaded_on: { en: "Downloaded On", hi: "डाउनलोड की तारीख", mr: "डाउनलोड दिनांक", ta: "பதிவிறக்கப்பட்ட தேதி" },
  view_details: { en: "View Details", hi: "विवरण देखें", mr: "तपशील पहा", ta: "விவரங்களை பார்க்க" },
  download_again: { en: "Download Again", hi: "फिर से डाउनलोड करें", mr: "पुन्हा डाउनलोड करा", ta: "மீண்டும் பதிவிறக்கவும்" },
  no_receipt_downloads: { en: "No downloaded receipts yet", hi: "अभी तक कोई डाउनलोड रसीद नहीं", mr: "अजून डाउनलोड पावत्या नाहीत", ta: "இன்னும் பதிவிறக்கப்பட்ட ரசீதுகள் இல்லை" },
  error_load_downloads: { en: "Unable to load downloads", hi: "डाउनलोड सूची लोड नहीं हो सकी", mr: "डाउनलोड यादी लोड करता आली नाही", ta: "பதிவிறக்கங்களை ஏற்ற முடியவில்லை" },
  error_download_receipt: { en: "Unable to download receipt", hi: "रसीद डाउनलोड नहीं हो सकी", mr: "पावती डाउनलोड करता आली नाही", ta: "ரசீதை பதிவிறக்க முடியவில்லை" },
  loading_payment_details: { en: "Loading payment details...", hi: "भुगतान विवरण लोड हो रहे हैं...", mr: "पेमेंट तपशील लोड होत आहेत...", ta: "கட்டண விவரங்கள் ஏற்றப்படுகின்றன..." },
  transaction_information: { en: "Transaction Information", hi: "लेनदेन जानकारी", mr: "व्यवहार माहिती", ta: "பரிவர்த்தனை தகவல்" },
  resident_information: { en: "Resident Information", hi: "निवासी जानकारी", mr: "निवासी माहिती", ta: "குடியிருப்பாளர் தகவல்" },
  name: { en: "Name", hi: "नाम", mr: "नाव", ta: "பெயர்" },
  phone: { en: "Phone", hi: "फोन", mr: "फोन", ta: "தொலைபேசி" },
  email: { en: "Email", hi: "ईमेल", mr: "ईमेल", ta: "மின்னஞ்சல்" },
  address: { en: "Address", hi: "पता", mr: "पत्ता", ta: "முகவரி" },
  aadhaar: { en: "Aadhaar", hi: "आधार", mr: "आधार", ta: "ஆதார்" },
  download_receipt_pdf: { en: "Download Receipt PDF", hi: "रसीद PDF डाउनलोड करें", mr: "पावती PDF डाउनलोड करा", ta: "ரசீது PDF பதிவிறக்கவும்" },
  error_load_payment_details: { en: "Unable to load payment details", hi: "भुगतान विवरण लोड नहीं हो सके", mr: "पेमेंट तपशील लोड करता आले नाहीत", ta: "கட்டண விவரங்களை ஏற்ற முடியவில்லை" },
  status: { en: "Status", hi: "स्थिति", mr: "स्थिती", ta: "நிலை" },
  receipt_mode: { en: "Receipt Mode", hi: "रसीद मोड", mr: "पावती मोड", ta: "ரசீது முறை" },
  receipt_mode_both: { en: "Both", hi: "दोनों", mr: "दोन्ही", ta: "இரண்டும்" },
  receipt_mode_digital: { en: "Digital", hi: "डिजिटल", mr: "डिजिटल", ta: "டிஜிட்டல்" },
  receipt_mode_print: { en: "Print", hi: "प्रिंट", mr: "प्रिंट", ta: "அச்சு" },
  payment_details: { en: "Payment Details", hi: "भुगतान विवरण", mr: "पेमेंट तपशील", ta: "கட்டண விவரங்கள்" },
  receipt_summary: { en: "Receipt and transaction summary", hi: "रसीद और लेनदेन सारांश", mr: "पावती आणि व्यवहार सारांश", ta: "ரசீது மற்றும் பரிவர்த்தனை சுருக்கம்" },
  payment_status: { en: "Payment Status", hi: "भुगतान स्थिति", mr: "पेमेंट स्थिती", ta: "கட்டண நிலை" },
  stripe_checkout: { en: "Stripe Checkout", hi: "स्ट्राइप चेकआउट", mr: "स्ट्राइप चेकआउट", ta: "ஸ்டிரைப் கட்டணச் சாளரம்" },
  payment_cancelled: { en: "Payment Cancelled", hi: "भुगतान रद्द", mr: "पेमेंट रद्द", ta: "கட்டணம் ரத்து செய்யப்பட்டது" },
  payment_cancelled_note: { en: "You can retry payment or return to services.", hi: "आप भुगतान फिर से कर सकते हैं या सेवाओं पर लौट सकते हैं।", mr: "तुम्ही पेमेंट पुन्हा करू शकता किंवा सेवांकडे परत जाऊ शकता.", ta: "நீங்கள் மீண்டும் கட்டணம் செலுத்தலாம் அல்லது சேவைகளுக்கு திரும்பலாம்." },
  retry: { en: "Retry", hi: "पुनः प्रयास", mr: "पुन्हा प्रयत्न", ta: "மீண்டும் முயற்சி" },
  payment_verifying: { en: "Verifying Payment", hi: "भुगतान सत्यापित किया जा रहा है", mr: "पेमेंट पडताळणी सुरू आहे", ta: "கட்டணம் சரிபார்க்கப்படுகிறது" },
  payment_verifying_wait: { en: "Please wait while we confirm your transaction.", hi: "कृपया प्रतीक्षा करें, हम आपके लेनदेन की पुष्टि कर रहे हैं।", mr: "कृपया थांबा, तुमचा व्यवहार पडताळला जात आहे.", ta: "உங்கள் பரிவர்த்தனையை உறுதிப்படுத்தும் வரை காத்திருக்கவும்." },
  unable_verify_payment: { en: "Unable to verify payment", hi: "भुगतान सत्यापित नहीं हो सका", mr: "पेमेंट पडताळता आले नाही", ta: "கட்டணத்தை சரிபார்க்க முடியவில்லை" },
  track_by_reference: { en: "Track by Reference", hi: "रेफरेंस से ट्रैक करें", mr: "संदर्भाने ट्रॅक करा", ta: "குறிப்பு எண் மூலம் கண்காணிக்கவும்" },
  stripe_session: { en: "Stripe Session", hi: "स्ट्राइप सत्र", mr: "स्ट्राइप सत्र", ta: "ஸ்டிரைப் அமர்வு" },
  txn_appear_shortly: { en: "Will appear shortly", hi: "शीघ्र दिखाई देगा", mr: "लवकरच दिसेल", ta: "விரைவில் தோன்றும்" },
  view_payment_details: { en: "View Payment Details", hi: "भुगतान विवरण देखें", mr: "पेमेंट तपशील पहा", ta: "கட்டண விவரம் பார்க்க" },
  download_receipt: { en: "Download Receipt", hi: "रसीद डाउनलोड करें", mr: "पावती डाउनलोड करा", ta: "ரசீதை பதிவிறக்கு" },
  downloading: { en: "Downloading...", hi: "डाउनलोड हो रहा है...", mr: "डाउनलोड सुरू आहे...", ta: "பதிவிறக்கப்படுகிறது..." },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<LangCode>(() => {
    const persisted = localStorage.getItem("kiosk_lang") as LangCode | null;
    return persisted || "en";
  });

  const setLang = (code: LangCode) => {
    localStorage.setItem("kiosk_lang", code);
    setLangState(code);
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string): string => translations[key]?.[lang] || translations[key]?.en || key;

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};


